apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: azkaban
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: prod
    app.kubernetes.io/version: 1
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: toxictv
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: toxictoast/toxictv-azkaban:latest
          ports:
            - containerPort: 3333
          env:
            - name: BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: azkaban-config
                  key: broker